name: rcmd

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "12.0"

settings:
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

targets:
  rcmd:
    type: tool
    platform: macOS
    sources:
      - path: rcmd.m
    dependencies:
        - sdk: Carbon.framework
