name: rcmd

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "12.0"

settings:
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

targets:
  rcmd:
    type: tool
    platform: macOS
    sources:
      - path: src/
      - path: project.yml
        type: folder
      - path: Makefile
        type: folder
      - path: README.md
        type: folder
      - path: test.py
        type: folder
    dependencies:
        - sdk: Carbon.framework
        - sdk: Cocoa.framework
